### PR TITLE
userscript for adding Mediawiker edit button to page

### PR DESCRIPTION
**Pull request by Plloi**
A userscript for those sites you can't/shouldn't edit page templates on.
Should work in most MediaWiki based wiki's, but currently has issues with wikia

### CODE REVIEW

**Comment by Plloi** [comment]
Note: Built & tested in chrome w/tampermonkey

**Comment by tosher** [comment]
Thank you! 

Can you add a small *readme.md* file with description of the script, and this moments:
* Small installation howto. (for chrome..)
* How to edit this script for using on another wiki sites. It' important because of **match** section used now for example sites only.

**Comment by Plloi** [comment]
Updated

**Comment by tosher** [comment]
It's great! Thanx!

**Pull request merged**
