### PR TITLE
Add syntaxhighlight snippet

### PR DESCRIPTION
**Pull request by rabin-io**
Writing `syntaxhighlight` each time was had for me and remembering the parameters as well, its ease to delete then type or copy paste each time.

### CODE REVIEW

**Comment by tosher** [comment]
Existed snippet for `code` tag:
```
<snippet>
	<content><![CDATA[
<source lang="${1}">${2:$TM_SELECTED_TEXT}</source>
]]></content>
<tabTrigger>wsrc</tabTrigger>
	<!-- Optional: Set a scope to limit where the snippet will trigger -->
<scope>text.html.mediawiki</scope>
<description>Mediawiker: Source tag</description>
</snippet>
```
I think, needs the same:
* Cursor positioning inside `lang` attr
* Remove `highlight` attr
* Maybe remove `start` too

**Comment by rabin-io** [comment]
Nice to know, didn't notice it until now. Also never used the `<source>` tag so probably that's the reason.

I think having the `highlight` & `start` dose not hurt, as I mention in the comment, it's easier to delete it then write it.

Don't you agree ?

**Comment by tosher** [comment]
All existed snippets are available in the `Edit panel` :)
I will check this attrs some time and then merge this request, ok?

**Comment by rabin-io** [comment]
Thanks. 

And thanks again for this great plugin `:)`

**Pull request merged**
