### PR TITLE
Prevent list definition from propagating through the entire document

### PR DESCRIPTION
**Pull request by gigamicro**
Sometimes ; is used for minor headers, this fixes not having a definition breaking all following formatting
(matches a segment, but is popping from the stack so it should be fine)

### CODE REVIEW

**Comment by tosher** [comment]
Thank you!

Please, could you post an example with this case?

I want to add a test to `syntax_test_MediawikiNG.mediawiki`

**Comment by gigamicro** [comment]
oh, sure!
```
;potential header
text ''italics'' '''bold'''

;label : item

; label
:item
```

**Comment by gigamicro** [comment]
Here's the whole syntax test, cleaned up bc I had some free time

[new_syntax_test_MediawikiNG.mediawiki](https://github.com/tosher/Mediawiker/files/6029373/new_syntax_test_MediawikiNG.mediawiki.txt)

**Comment by gigamicro** [comment]
I added another fix relating to Image definitions

**Pull request closed without merging**
