### PR TITLE
No Lua syntax for Module:* subpages (ex: Module:Test/doc)

### PR DESCRIPTION
**Pull request by Adadov**
Module pages are using Lua syntax but their subpages are not.
So we need to keep Mediawiki NG syntax for them.

### CODE REVIEW

**Comment by tosher** [comment]
But, for example:
* https://en.wikipedia.org/wiki/Module:Bananas/testcases
Is a lua script :)

**Comment by Adadov** [comment]
Hum right ... So maybe just excluding /doc* ...

**Comment by tosher** [comment]
* Syntax method was rewritten - now it based on page namespace, not on page prefix (language independence).
* Exception for */doc* subpage was added.
Please, try the new version: 3.0.6

**Comment by Adadov** [comment]
Works great ! Thank you for the fast reaction !

**Pull request closed without merging**
